// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.12
// source: stream.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// StreamServiceClient is the client API for StreamService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type StreamServiceClient interface {
	Transfer(ctx context.Context, opts ...grpc.CallOption) (StreamService_TransferClient, error)
}

type streamServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewStreamServiceClient(cc grpc.ClientConnInterface) StreamServiceClient {
	return &streamServiceClient{cc}
}

func (c *streamServiceClient) Transfer(ctx context.Context, opts ...grpc.CallOption) (StreamService_TransferClient, error) {
	stream, err := c.cc.NewStream(ctx, &StreamService_ServiceDesc.Streams[0], "/proto.StreamService/Transfer", opts...)
	if err != nil {
		return nil, err
	}
	x := &streamServiceTransferClient{stream}
	return x, nil
}

type StreamService_TransferClient interface {
	Send(*PacketData) error
	Recv() (*PacketData, error)
	grpc.ClientStream
}

type streamServiceTransferClient struct {
	grpc.ClientStream
}

func (x *streamServiceTransferClient) Send(m *PacketData) error {
	return x.ClientStream.SendMsg(m)
}

func (x *streamServiceTransferClient) Recv() (*PacketData, error) {
	m := new(PacketData)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// StreamServiceServer is the server API for StreamService service.
// All implementations must embed UnimplementedStreamServiceServer
// for forward compatibility
type StreamServiceServer interface {
	Transfer(StreamService_TransferServer) error
	mustEmbedUnimplementedStreamServiceServer()
}

// UnimplementedStreamServiceServer must be embedded to have forward compatible implementations.
type UnimplementedStreamServiceServer struct {
}

func (UnimplementedStreamServiceServer) Transfer(StreamService_TransferServer) error {
	return status.Errorf(codes.Unimplemented, "method Transfer not implemented")
}
func (UnimplementedStreamServiceServer) mustEmbedUnimplementedStreamServiceServer() {}

// UnsafeStreamServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StreamServiceServer will
// result in compilation errors.
type UnsafeStreamServiceServer interface {
	mustEmbedUnimplementedStreamServiceServer()
}

func RegisterStreamServiceServer(s grpc.ServiceRegistrar, srv StreamServiceServer) {
	s.RegisterService(&StreamService_ServiceDesc, srv)
}

func _StreamService_Transfer_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(StreamServiceServer).Transfer(&streamServiceTransferServer{stream})
}

type StreamService_TransferServer interface {
	Send(*PacketData) error
	Recv() (*PacketData, error)
	grpc.ServerStream
}

type streamServiceTransferServer struct {
	grpc.ServerStream
}

func (x *streamServiceTransferServer) Send(m *PacketData) error {
	return x.ServerStream.SendMsg(m)
}

func (x *streamServiceTransferServer) Recv() (*PacketData, error) {
	m := new(PacketData)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// StreamService_ServiceDesc is the grpc.ServiceDesc for StreamService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StreamService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.StreamService",
	HandlerType: (*StreamServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Transfer",
			Handler:       _StreamService_Transfer_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "stream.proto",
}
