// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddServerConfig(arg1:any):Promise<void>;

export function ChangeDirectTo(arg1:string):Promise<void>;

export function ChangeGlobalTo(arg1:string):Promise<void>;

export function DeleteServerConfig(arg1:string):Promise<void>;

export function ListKcpCrypts():Promise<Array<string>>;

export function ListKcpModes():Promise<Array<string>>;

export function ListMethods():Promise<Array<string>>;

export function ListOutboundInterfaces():Promise<Array<string>>;

export function ListSSRObfs():Promise<Array<string>>;

export function ListSSRProtocols():Promise<Array<string>>;

export function ListTransports():Promise<Array<string>>;

export function LoadConfig():Promise<any>;

export function SaveConfig(arg1:any):Promise<void>;

export function SpeedTest(arg1:string):Promise<string>;

export function StartServer(arg1:any):Promise<void>;

export function StopServer():Promise<void>;

export function UpdateServerConfig(arg1:any):Promise<void>;
