// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddServerConfig(arg1) {
  return window['go']['main']['App']['AddServerConfig'](arg1);
}

export function ChangeDirectTo(arg1) {
  return window['go']['main']['App']['ChangeDirectTo'](arg1);
}

export function ChangeGlobalTo(arg1) {
  return window['go']['main']['App']['ChangeGlobalTo'](arg1);
}

export function DeleteServerConfig(arg1) {
  return window['go']['main']['App']['DeleteServerConfig'](arg1);
}

export function ListKcpCrypts() {
  return window['go']['main']['App']['ListKcpCrypts']();
}

export function ListKcpModes() {
  return window['go']['main']['App']['ListKcpModes']();
}

export function ListMethods() {
  return window['go']['main']['App']['ListMethods']();
}

export function ListOutboundInterfaces() {
  return window['go']['main']['App']['ListOutboundInterfaces']();
}

export function ListSSRObfs() {
  return window['go']['main']['App']['ListSSRObfs']();
}

export function ListSSRProtocols() {
  return window['go']['main']['App']['ListSSRProtocols']();
}

export function ListTransports() {
  return window['go']['main']['App']['ListTransports']();
}

export function LoadConfig() {
  return window['go']['main']['App']['LoadConfig']();
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function SpeedTest(arg1) {
  return window['go']['main']['App']['SpeedTest'](arg1);
}

export function StartServer(arg1) {
  return window['go']['main']['App']['StartServer'](arg1);
}

export function StopServer() {
  return window['go']['main']['App']['StopServer']();
}

export function UpdateServerConfig(arg1) {
  return window['go']['main']['App']['UpdateServerConfig'](arg1);
}
