server:
  - name: ss
    addr: 127.0.0.1:8388
    password: "12345" 
    # method: chacha20-ietf-poly1305
    method: none
    transport: ssh 
    ssh:
      user: root
      # password: root
      private_key: ssh-keys/test-key
      public_key: ssh-keys/test-key.pub
  
local:
  socks_addr: 127.0.0.1:10086
  http_addr: 127.0.0.1:10087
  mixed_addr: 127.0.0.1:10088
log:
  color: true
  log_level: trace
  verbose_level: 2
iface: en5
auto_detect_iface: true
rules:
  mode: global
  global_to: 'ss'
  direct_to: ''

