server:
  - name: ss
    addr: 127.0.0.1:8388
    password: '12345'
    method: chacha20-ietf-poly1305
    transport: quic
    quic:
      conns: 3
      keep_alive: 5
      max_idle_timeout: 0
      handshake_idle_timeout: 0
      tls:
        mode: "tls"
        cert_path: "certs/client.crt"
        key_path: "certs/client.key"
        ca_path: "certs/ca.crt"
        hostname: www.helloworld.com
local:
  socks_addr: 127.0.0.1:10086
  http_addr: 127.0.0.1:10087
  mixed_addr: 127.0.0.1:10088
log:
  color: true
  log_level: trace
  verbose_level: 2
iface: en5
auto_detect_iface: true
rules:
  mode: global
  global_to: ss 
  direct_to: ''
