server:
  - name: ss
    addr: 127.0.0.1:8388
    password: '12345'
    method: chacha20-ietf-poly1305
    transport: quic
    quic:
      conns: 3
local:
  socks_addr: 127.0.0.1:10086
  http_addr: 127.0.0.1:10087
color: true
verbose: true
verbose_level: 2
iface: en5
auto_detect_iface: true
rules:
  mode: global
  global_to: ss 
  direct_to: ''
