server:
  - name: ss
    addr: ':8388'
    password: '12345'
    method: chacha20-ietf-poly1305
    transport: quic
    quic:
      conns: 3
      tls:
        mode: "tls"
        cert_path: "certs/server.crt"
        key_path: "certs/server.key"
        ca_path: "certs/ca.crt"
log:
  color: true
  log_level: trace
  verbose_level: 2

