server:
  - name: ss
    addr: ':8388'
    password: '12345'
    method: chacha20-ietf-poly1305
    transport: kcp
    kcp:
      crypt: aes-128
      key: '12345'
      mode: fast2
      compress: false
      conns: 3
log:
  color: true
  log_level: trace
  verbose_level: 3

# iface: en5
# auto_detect_iface: true