server:
  - name: ss
    addr: ':8388'
    password: "12345"
    # method: chacha20-ietf-poly1305
    method: none
    transport: grpc
    grpc:
      send_buffer_size: 4096
      receive_buffer_size: 4096
      tls:
        mode: ""
        cert_path: "certs/server.crt"
        key_path: "certs/server.key"
        ca_path: "certs/ca.crt"
log:
  color: true
  log_level: debug
  verbose_level: 3
