server:
  - name: ss
    addr: 127.0.0.1:8388
    password: '12345'
    method: aes-128-cfb
    transport: default
    udp: true
local:
  socks_addr: 127.0.0.1:10086
  http_addr: 127.0.0.1:10087
  socks_auth: '123:123'
  http_auth: '123:123'
color: true
verbose: true
verbose_level: 2
iface: en5
auto_detect_iface: true
rules:
  mode: global
  direct_to: ''
  global_to: 'ss'
