server:
  - name: ss
    addr: ':8388'
    password: '12345'
    method: aes-128-cfb
    # method: none
    transport: default
    udp: true
log:
  color: true
  log_level: trace
  verbose_level: 3

# iface: en5
auto_detect_iface: true