server:
  - name: local-ssr
    type: ssr
    addr: 127.0.0.1:8388
    password: password
    method: aes-256-cfb
    transport: default
    ssr:
      protocol: auth_chain_a
      protocol_param: ''
      obfs: tls1.2_ticket_auth
      obfs_param: ''
local:
  socks_addr: 127.0.0.1:10086
  http_addr: 127.0.0.1:10087
  mixed_addr: 127.0.0.1:10088
  system_proxy: true
log:
  color: true
  log_level: trace
  verbose_level: 3
iface: en5
auto_detect_iface: true
rules:
  mode: global
