local:
  mixed_addr: :10088
  mitm:
    enable: true
    proxy: http://127.0.0.1:7900
    ca_path: "certs/ca.crt"
    key_path: "certs/ca.key"
    fake_cert_pool:
      capacity: 2048
      interval_second: 30
      expire_second: 15
    # disable_http2: true
    # skip_verify_ssl_from_server: true
    root_ca_certs:
      - /tmp/curl_ca.crt
    client_certs:
      "127.0.0.1":
        cert_path: /tmp/curl_client.crt
        key_path: /tmp/curl_client.key
  tun:
    enable: true
    name: ""
    cidr: 198.18.0.1/16
    mtu: 9000
    auto_route: true
    dns_hijack:
      - 8.8.8.8:53 
      - any:53
  dns:
    listen: ':5380'
    disable_rewrite: true
    nameservers:
      - 8.8.8.8
      - 114.114.114.114
log:
  color: true
  log_level: trace
  verbose_level: 1

# iface: lo
auto_detect_iface: true
