server:
  - name: ss
    addr: 127.0.0.1:8388
    password: "12345"
    method: aes-128-cfb
    # method: none
    transport: default
    udp: true
local:
  socks_addr: :10086
  http_addr: :10087
  mixed_addr: :10088
  # socks_auth: "123:123"
  # http_auth: '123:123'
  lookup_hostsfile: true
log:
  color: true
  log_level: trace
  verbose_level: 2
# iface: lo
# auto_detect_iface: true
rules:
  mode: global
  direct_to: ""
  global_to: "ss"
