// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddServerConfig(arg1) {
  return window['go']['main']['App']['AddServerConfig'](arg1);
}

export function DeleteServerConfig(arg1) {
  return window['go']['main']['App']['DeleteServerConfig'](arg1);
}

export function ExportCurrentConfig() {
  return window['go']['main']['App']['ExportCurrentConfig']();
}

export function GetAllInterfaceName() {
  return window['go']['main']['App']['GetAllInterfaceName']();
}

export function GetJsonConfig() {
  return window['go']['main']['App']['GetJsonConfig']();
}

export function GetJsonConfigContent() {
  return window['go']['main']['App']['GetJsonConfigContent']();
}

export function GetJsonConfigFilePath() {
  return window['go']['main']['App']['GetJsonConfigFilePath']();
}

export function GetSupportCipherMethods() {
  return window['go']['main']['App']['GetSupportCipherMethods']();
}

export function GetSupportKcpCrypts() {
  return window['go']['main']['App']['GetSupportKcpCrypts']();
}

export function GetSupportKcpModes() {
  return window['go']['main']['App']['GetSupportKcpModes']();
}

export function GetSupportTransportTypes() {
  return window['go']['main']['App']['GetSupportTransportTypes']();
}

export function LoadConfig() {
  return window['go']['main']['App']['LoadConfig']();
}

export function LoadConfigFile(arg1) {
  return window['go']['main']['App']['LoadConfigFile'](arg1);
}

export function Ping(arg1) {
  return window['go']['main']['App']['Ping'](arg1);
}

export function SaveLocalConfig(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveLocalConfig'](arg1, arg2, arg3);
}

export function SpeedTest() {
  return window['go']['main']['App']['SpeedTest']();
}

export function StartServer() {
  return window['go']['main']['App']['StartServer']();
}

export function StopServer() {
  return window['go']['main']['App']['StopServer']();
}

export function StopSpeedTest() {
  return window['go']['main']['App']['StopSpeedTest']();
}

export function TcpPing(arg1) {
  return window['go']['main']['App']['TcpPing'](arg1);
}

export function UpdateServerConfig(arg1) {
  return window['go']['main']['App']['UpdateServerConfig'](arg1);
}
