// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {config} from '../models';

export function AddServerConfig(arg1:config.ServerJsonConfig):Promise<void>;

export function DeleteServerConfig(arg1:string):Promise<void>;

export function ExportCurrentConfig():Promise<void>;

export function GetAllInterfaceName():Promise<Array<string>>;

export function GetJsonConfig():Promise<config.JsonConfig>;

export function GetJsonConfigContent():Promise<string>;

export function GetJsonConfigFilePath():Promise<string>;

export function GetSupportCipherMethods():Promise<Array<string>>;

export function GetSupportKcpCrypts():Promise<Array<string>>;

export function GetSupportKcpModes():Promise<Array<string>>;

export function GetSupportTransportTypes():Promise<Array<string>>;

export function LoadConfig():Promise<config.JsonConfig>;

export function LoadConfigFile(arg1:string):Promise<config.JsonConfig>;

export function Ping(arg1:string):Promise<string>;

export function SaveLocalConfig(arg1:config.LocalJsonConfig,arg2:string,arg3:boolean):Promise<void>;

export function SpeedTest():Promise<string>;

export function StartServer():Promise<void>;

export function StopServer():Promise<void>;

export function StopSpeedTest():Promise<void>;

export function TcpPing(arg1:string):Promise<string>;

export function UpdateServerConfig(arg1:config.ServerJsonConfig):Promise<void>;
